server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://103.56.163.94:3306/gbluxurydb
    username: devuser
    password: "giabao#250119"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: tcnhpts@gmail.com
    password: oohi mjhl rgke opjt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

minio:
  url: http://103.56.163.94:9000
  access-key: L1cbVODxS4OSGMbsgagW
  secret-key: dlEcWdyBythhQ36xB4yjIqJORUHDUTBFV5tQcxnX
  bucket-name: gb-bucket-2025

java:
  awt:
    headless: true
